### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-EditorExtensions#12] opened 2020-04-27 20:26 UTC
![20200427232405_1](https://user-images.githubusercontent.com/61344188/80417425-682b3200-88de-11ea-8753-2d8c5f8a01d3.jpg)

Happens when entering editor mode from sandbox mode. Running Creative mode at the same time.

**Comment by raiguard** [comment] 2020-04-27 20:28
Duplicate of #9.

**Closed by raiguard** 2020-04-27 20:28 UTC
