### ISSUE TITLE
Infinity Cargo Wagon crashes consistently when opening its GUI

### ISSUE THREAD

**Issue by carter-thaxton** [raiguard/Factorio-EditorExtensions#45] opened 2020-12-17 05:54 UTC
#### Describe the Bug

I'm getting this error consistently when clicking on an Infinity Cargo Wagon.

The mod Editor Extensions (1.9.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_gui_opened (ID 84)
__EditorExtensions__/scripts/entity/infinity-wagon.lua:90: attempt to index local 'player' (a number value)
stack traceback:
	__EditorExtensions__/scripts/entity/infinity-wagon.lua:90: in function 'open'
	__EditorExtensions__/control.lua:381: in function <__EditorExtensions__/control.lua:358>

#### To Reproduce

1. Create an Infinity Cargo Wagon
2. Place it on a track
3. Click on it
4. Crash

**Comment by carter-thaxton** [comment] 2020-12-17 05:55
I don't recall running into this until the most recent update.

**Comment by raiguard** [comment] 2020-12-17 06:08
Already fixed for the next version, which I'm releasing... right now!

Duplicate of #44

**Closed by raiguard** 2020-12-17 06:08 UTC
Labels: bug
