### ISSUE TITLE
Crash when creating blueprint

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [raiguard/Factorio-EditorExtensions#38] opened 2020-11-15 04:49 UTC
Editor extensions causes a non-recoverable error when creating a blueprint and pressing shift

#### To Reproduce

take blueprint from book in the library
Select the rails on the far bottom left while pressing shift
Crash

AmericanPatriot

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5541870/factorio-current.log)
[1 Testing And Design World.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5541873/1.Testing.And.Design.World.zip)

**Comment by raiguard** [comment] 2020-11-16 20:26
Ah... this is actually an API limitation that there is no solution for. I can fix the crash, but instead, you'll have a blueprint that has some really weird crap in it if you select an infinity loader. And infinity wagon filters won't be preserved.

Basically, don't use a blank blueprint directly from the library - it doesn't work with mods whatsoever and the developers have shown zero interest in fixing it.

**Comment by raiguard** [comment] 2020-11-16 20:36
Ok, WTF, it's not crashing anymore. For some reason now, `player.blueprint_to_setup` is returning a LuaItemStack for the blueprint even when you're holding it from the library (where it's not an actual item). Trying to reproduce the crash again is failing, even though I reproduced it once before.

I am so confused...

**Comment by raiguard** [comment] 2020-11-29 00:53
I can't reproduce it anymore. Very strange.

**Comment by raiguard** [comment] 2020-11-29 23:06
I'm going to close this for now. Please let me know if it happens to you again.

**Closed by raiguard** 2020-11-29 23:06 UTC
Labels: bug, cannot reproduce
