### ISSUE TITLE
Inventory sync crash

### ISSUE THREAD

**Issue by yeah-toast** [raiguard/Factorio-EditorExtensions#14] opened 2020-04-29 17:28 UTC
Just had a crash as soon as I attempted to open the Editor menu on one of my sandbox maps.  I was able to open it on others without issue.

```
The mod Editor Extensions (1.4.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::ee-toggle-map-editor (ID 161)
The mod Editor Extensions (1.4.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_player_toggled_map_editor (ID 116)
__EditorExtensions__/scripts/inventory.lua:82: attempt to get length of local 'sync_inventory' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/inventory.lua:82: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
	[C]: in function 'toggle_map_editor'
	__EditorExtensions__/control.lua:196: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	__EditorExtensions__/control.lua:196: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	[C]: in function 'toggle_map_editor'
	__EditorExtensions__/control.lua:196: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
```

**Comment by raiguard** [comment] 2020-04-29 17:37
Duplicate of #9. I'll re-open that issue so people will see it.

**Closed by raiguard** 2020-04-29 17:37 UTC
